name: Publish Mod
on:
  workflow_dispatch:
    inputs:
      version_number:
        type: string
        description: "Version Number"
        required: true

      release_github:
        type: boolean
        description: "Github Release"
        default: false

      release_modrinth:
        type: boolean
        description: "Modrinth Release"
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: Build Mod
        run: ./gradlew clean build

      - name: Publish to GitHub
        if: ${{ inputs.release_github == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version_number }}
          files: build/libs/*.jar

