name: Publish Mod
on:
  workflow_dispatch:
    inputs:
      version_number:
        type: string
        description: "Version Number"
        required: true

      release_github:
        type: boolean
        description: "Github Release"
        default: false

      release_modrinth:
        type: boolean
        description: "Modrinth Release"
        default: false

env:
  JAVA_VERSION=21

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish to GitHub
        if: ${{ inputs.release_github == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version_number }}
          files: build/libs/*.jar

